config/routes.rb
Urdb::Application.routes.draw do

  root 'films#index'

  get '/new' => 'films#new' 
   
  get '/films' => 'films#index'

  get '/:film' => 'films#show', as: 'film'

  get '/films/:id'  => 'films#show_id', as: 'film_id'

end

app/models/film.rb
class Film < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.all
  end

  def show
    title = params[:film]
    @film =  Film.find_by_title(title)

    redirect_to film_id_path(@film.id)
  end

  def show_id

    id = params[:id]
    @film = Film.find(id)

  end

  def new
  end

  def create

     render text: params[:film].inspect
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/films/index.html.erb
<h1> Film list </h1>
<ul>
  <% @films.each do |film| %>
  <li> <%= link_to image_tag(film.poster , size: "490x200", alt: "#{film.title}"), film_id_path(film.id)  %>
  <% end %> 
</ul>

app/views/films/new.html.erb
<h1> Add Film to Database </h1>

<%= form_for :film, url: films_path do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p> 
    <%= f.label :director %>
    <%= f.text_field :director %>
  </p>
  <p> 
    <%= f.label :poster %>
    <%= f.url_field :poster %>
  </p>
  <p> 
    <%= f.label :open %>
    <%= f.date_field :open %>
  </p>
  <p> 
    <%= f.label :synopsis %>
    <%= f.text_area :synopsis, size: "60x12" %>
  </p>
  <p> 
    <%= f.label :trailer %>
    <%= f.text_field :trailer %>
  </p>
  <p> 
    <%= f.label :budget %>
    <%= f.text_field :budget %>
  </p>
   <p> 
    <%= f.label :gross %>
    <%= f.text_field :gross %>
  </p>
  <p> 
    <%= f.submit "Create" %>
  </p>
<% end %>

app/views/films/show.html.erb
<h1><%= @film.title %></h1>
<h2>A film by <%= @film.director %></h2>
<%= image_tag(@film.poster)%>
<p>Worldwide Premier<%= @film.open %> </p>
<p><strong>Synopsis:</strong><%= @film.synopsis %></p>

<iframe width="900" height="540" src=<%= "//www.youtube.com/embed/#{@film.trailer}" %> frameborder="0" allowfullscreen>
</iframe>
<p> Budget: $<%= @film.budget %> </p>
<p>Worldwide Gross $<%= @film.gross %> </p>

<%= link_to "Home", root_path %>

app/views/films/show_id.html.erb
<h1><%= @film.title %></h1>
<h2>A film by <%= @film.director %></h2>
<%= image_tag(@film.poster)%>
<p>Worldwide Premier<%= @film.open %> </p>
<p><strong>Synopsis:</strong><%= @film.synopsis %></p>

<iframe width="900" height="540" src=<%= "//www.youtube.com/embed/#{@film.trailer}" %> frameborder="0" allowfullscreen>
</iframe>
<p> Budget: $<%= @film.budget %> </p>
<p>Worldwide Gross $<%= @film.gross %> </p>

<%= link_to "Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Urdb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>